In [2]:
import numpy as np

## Numpy functions
1. array
2. zeros
3. ones
4. eye
5. arange
6. linspace
7. random.rand

In [4]:
mylist = [1,2,3,4,5]
my_array = np.array(mylist)
print(my_array)
print(type(my_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
abc = np.zeros(10)
print(abc)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
one_array = np.ones(3)
print(one_array)

[1. 1. 1.]


In [11]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
range_arr = np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]


In [ ]:
# Use to calculate equal distance
spaced = np.linspace(10,20, 5)  
print(spaced)

[10.  12.5 15.  17.5 20. ]


In [14]:
mat = np.random.rand(2,2)
print(mat)

[[0.20688433 0.75931578]
 [0.32026118 0.12757582]]


## Array Operations
1. Array reshape

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
sum_arr = arr1 + arr2
product_arr = arr1 * arr2
print(sum_arr)
print(product_arr)

[5 7 9]
[ 4 10 18]


In [25]:
# Array Reshape
my_list = [1, 2, 3, 4, 5, 6]
my_array = np.array(my_list)
reshaped_arr = my_array.reshape(1, 6)
print(reshaped_arr)  

[[1 2 3 4 5 6]]


In [26]:
reshaped_arr = my_array.reshape(2, 3)
print(reshaped_arr)  

[[1 2 3]
 [4 5 6]]


. apache spark

# Pandas

In [1]:
import pandas as pd

data = [10, 20, 30, 40, 50]
series = pd.Series(data, name = "xyz series")
series

0    10
1    20
2    30
3    40
4    50
Name: xyz series, dtype: int64

In [3]:
data = {
    'Name': ['Ved', "Raj", "Pritam"],
    'Age': [20, 21, 19],
    'Gender': ['Male', 'Female', 'Male']
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Gender
0     Ved   20    Male
1     Raj   21  Female
2  Pritam   19    Male


In [4]:
df = pd.read_csv(r"DataSets/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1