In [2]:
import numpy as np

## Numpy functions
1. array
2. zeros
3. ones
4. eye
5. arange
6. linspace
7. random.rand

In [4]:
mylist = [1,2,3,4,5]
my_array = np.array(mylist)
print(my_array)
print(type(my_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
abc = np.zeros(10)
print(abc)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
one_array = np.ones(3)
print(one_array)

[1. 1. 1.]


In [11]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
range_arr = np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]


In [ ]:
# Use to calculate equal distance
spaced = np.linspace(10,20, 5)  
print(spaced)

[10.  12.5 15.  17.5 20. ]


In [14]:
mat = np.random.rand(2,2)
print(mat)

[[0.20688433 0.75931578]
 [0.32026118 0.12757582]]


## Array Operations
1. Array reshape

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
sum_arr = arr1 + arr2
product_arr = arr1 * arr2
print(sum_arr)
print(product_arr)

[5 7 9]
[ 4 10 18]


In [25]:
# Array Reshape
my_list = [1, 2, 3, 4, 5, 6]
my_array = np.array(my_list)
reshaped_arr = my_array.reshape(1, 6)
print(reshaped_arr)  

[[1 2 3 4 5 6]]


In [26]:
reshaped_arr = my_array.reshape(2, 3)
print(reshaped_arr)  

[[1 2 3]
 [4 5 6]]


. apache spark

# Pandas

In [1]:
import pandas as pd

data = [10, 20, 30, 40, 50]
series = pd.Series(data, name = "xyz series")
series

0    10
1    20
2    30
3    40
4    50
Name: xyz series, dtype: int64

In [3]:
data = {
    'Name': ['Ved', "Raj", "Pritam"],
    'Age': [20, 21, 19],
    'Gender': ['Male', 'Female', 'Male']
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Gender
0     Ved   20    Male
1     Raj   21  Female
2  Pritam   19    Male


In [4]:
df = pd.read_csv(r"DataSets/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
df.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1

In [7]:
df.tail(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
766                     0.349   47        1  
767                     0.315   23        0

In [8]:
df.shape

(768, 9)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [10]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [11]:
## detect Missing values
df.isna()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [17]:
import numpy as np
data = {
    "Name":["Raj","Vedant","Swayam","Sandeep"],
    "Age":[28, np.nan, 25, 22]
}
df = pd.DataFrame(data)
df

Name   Age
0      Raj  28.0
1   Vedant   NaN
2   Swayam  25.0
3  Sandeep  22.0

In [18]:
df.isna()

Name    Age
0  False  False
1  False   True
2  False  False
3  False  False

In [19]:
mean_age = df["Age"].mean()
df["Age"].fillna(mean_age, inplace=True)
df

C:\Users\mahaj\AppData\Local\Temp\ipykernel_5908\781068387.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(mean_age, inplace=True)


Name   Age
0      Raj  28.0
1   Vedant  25.0
2   Swayam  25.0
3  Sandeep  22.0

In [20]:
df.drop_duplicates()

Name   Age
0      Raj  28.0
1   Vedant  25.0
2   Swayam  25.0
3  Sandeep  22.0